### ISSUE TITLE
Request for complete file

### ISSUE THREAD

**Issue by Kaustubh-1420** [ashutoshsahoo/python-graphql-todo-api#2]
Hi. I was exploring your code in order to understand graphql apis better. your code was the only one specific to my needs(flask Ariadne , graphql) so I want to request the missing files, the queries and mutations folder. sry I wrote this request as a issue I have never used GitHub before

**Comment by ashutoshsahoo** [comment]
@Kaustubh-1420 , [schema.graphql](https://github.com/ashutoshsahoo/python-graphql-todo-api/blob/main/schema.graphql) contains all the queries and mutations.
